package com.mikeschvedov.gamingtrackerms

class AllGameList {
    companion object{

        val allGameList = mutableListOf(
            Game(
                "Modern Warfare - Warzone",
                "1089",
                R.drawable.warzone,
                100,
                "28/28",
                true,
                true,
                "Realism 5/5",
                "",
                "",
                "",
                "Story - 20",
                "Multiplayer - 391",
                "Warzone - 678"
            ),
            Game(
                "Aion",
                "332",
                R.drawable.aion,
                null,
                "",
                false,
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            ),
            Game(
                "Red Dead Redemption 2",
                "287",
                R.drawable.rdr2,
                100,
                "51/51",
                true,
                true,
                "",
                "",
                "",
                "",
                "Story - 195",
                "Multiplayer - 92",
                ""
            ),
            Game(
                "Playerunknown's Battlegrounds",
                "181",
                R.drawable.pubg,
                45,
                "17/37",
                true,
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            ),
            Game(
                "Star Wars: The Old Republic",
                "152",
                R.drawable.star,
                27,
                "53/191",
                false,
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            ),
            Game(
                "Battlefield 4",
                "+100",
                R.drawable.bf4,
                70,
                "",
                true,
                true,
                "Hard 3/3",
                "",
                "",
                "",
                "PS3 - 60 (minimum)",
                "PC(old) - 40",
                ""
            ),
            Game(
                "Stardew Valley",
                "91:30",
                R.drawable.stardew_valley,
                70,
                "28/40",
                false,
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            ),
            Game(
                "Dying Light",
                "85",
                R.drawable.dying_light,
                84,
                "62/69",
                true,
                true,
                "+ The Following DLC",
                "",
                "",
                "",
                "",
                "",
                ""
            ),
            Game(
                "My Time at Portia",
                "65",
                R.drawable.portia,
                54,
                "50/91",
                false,
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            ),

            Game(
                "The Division 2",
                "65",
                R.drawable.disivion2,
                54,
                "32/61",
                false,
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            ),
            Game(
                "Oxygen Not Included",
                "62",
                R.drawable.oxygen,
                60,
                "21/35",
                false,
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            ),
            Game(
                "Commandos 2",
                "+60",
                R.drawable.commandos2,
                100,
                "22/22",
                true,
                true,
                "Very Hard 3/3",
                "",
                "",
                "",
                "Last full playthrough - 24",
                "2 old playthroughs ~ +36",
                ""
            ),
            Game(
                "Red Alert 2 + Yuri's Revenge",
                "54",
                R.drawable.ra2,
                null,
                "",
                true,
                false,
                "Hard 3/3",
                "",
                "",
                "",
                "Red Alert 2 ~ 40",
                "Yuri's Revenge - 13",
                "Skirmish - 1"
            ),
            Game(
                "PC Building Simulator",
                "48",
                R.drawable.pc,
                55,
                "41/74",
                false,
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            ),
            Game(
                "Horizon Zero Dawn",
                "47",
                R.drawable.hzd,
                96,
                "76/79",
                true,
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            ),
            Game(
                "Grand Theft Auto 5",
                "46",
                R.drawable.gta5,
                15,
                "12/77",
                true,
                false,
                "Story completed \n on FPS only",
                "",
                "",
                "",
                "Story - 29",
                "Online - 17",
                ""
            ),
            Game(
                "Battlefield 5",
                "45",
                R.drawable.bf5,
                100,
                "21/21",
                true,
                true,
                "Hardcore 4/4",
                "",
                "",
                "",
                "Story - 10",
                "Multiplayer - 31",
                "Multiplayer(PC) - 4"
            ),
            Game(
                "The Sims 4",
                "39",
                R.drawable.sims,
                100,
                "51/51",
                true,
                true,
                "",
                "",
                "",
                "",
                "PS4 Platinum - 37",
                "PC For Fun - 2",
                ""
            ),

            Game(
                "No Man's Sky",
                "38",
                R.drawable.sky,
                100,
                "27/27",
                true,
                true,
                "Permadeath 4/4",
                "",
                "",
                "",
                "",
                "",
                ""
            ),

            Game(
                "Subnautica",
                "34",
                R.drawable.sub,
                100,
                "17/17",
                true,
                true,
                "Survival 2/3",
                "",
                "",
                "",
                "New Save(Platinum) - 21",
                "Old Save - 12",
                ""
            ),
            Game(
                "Shadow Tactics: Blades of the Shogun",
                "33",
                R.drawable.tactics,
                86,
                "38/44",
                true,
                false,
                "Hardcore 3/3",
                "",
                "",
                "",
                "",
                "",
                ""
            ),
            Game(
                "Pokemon: SoulSilver",
                "30",
                R.drawable.soul,
                null,
                "",
                true,
                false,
                "Defeated Red",
                "",
                "",
                "",
                "",
                "",
                ""
            ),
            Game(
                "Star Wars: Jedi Fallen Order",
                "28:40",
                R.drawable.jedi,
                100,
                "39/39",
                true,
                true,
                "",
                "",
                "",
                "",
                "New Playthrough(Steam) - 23:40 ",
                "First Try(PS4) - 5:00 ",
                ""
            ),

            Game(
                "Pokemon: Let's Go Eevee",
                "24",
                R.drawable.eevee,
                null,
                "",
                true,
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            ),

            Game(
                "Grounded",
                "15",
                R.drawable.grounded,
                21,
                "6/28",
                false,
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            ),

            Game(
                "Pokemon TCG",
                "12",
                R.drawable.ptcgo,
                null,
                "",
                false,
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            ),

            Game(
                "House Flipper",
                "10",
                R.drawable.flipper,
                11,
                "7/61",
                false,
                false,
                "All DLC's Trophies",
                "Assembly Mode - Hard",
                "",
                "",
                "",
                "",
                ""
            ),
            Game(
                "Star Wars: Battlefront 2",
                "?",
                R.drawable.battlefront2,
                89,
                "0/41",
                true,
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            ),
            Game(
                "Elden Ring",
                "5:50",
                R.drawable.elden,
                2,
                "1/42",
                true,
                false,
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            ),
            Game(
                "Watch Dogs 2",
                "?",
                R.drawable.watchdogs,
                85,
                "50/56",
                true,
                true,
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            ),
            Game(
                "Days Gone",
                "?",
                R.drawable.days_gone,
                70,
                "?/?",
                true,
                true,
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            ),
            Game(
                "Spider-Man",
                "?",
                R.drawable.spiderman,
                62,
                "51/51",
                true,
                true,
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            ),



            )

    }
}